### PR TITLE
Initial Setup

### PR DESCRIPTION
**Pull request by NickHeiner**
This PR looks huge but it's actually pretty small. If you review the commits one at a time, you'll see that I didn't actually do much original work for this PR. 

* 2e1268f is just running `create-react-app`
* c796191 is just ejecting

* 21a1e27 and e58a16c are the actual things I did.

### CODE REVIEW

**Comment by CaptainStack** [comment]
What's with that generator in App.js?

**Comment by NickHeiner** [comment]
Lol oops. That was just me testing that the lint rules are working. It will be removed.

**Comment by CaptainStack** [comment]
Looks good to me.

**Comment by NickHeiner** [comment]
Cool – would you mind hitting the green "approve review" button? I've found that it's valuable to have an unambiguous way to signal accepting a PR.

**Pull request merged**
